### ISSUE TITLE
Missing step with restartButton in GameOver.ccb

### ISSUE THREAD

**Issue by airrick213** [MakeSchool-Tutorials/Sushi-Neko-SpriteBuilder-Swift#12]
The restart button should have a Doc root var value of restartButton

**Comment by heratyian** [comment]
I had the same issue. App crashed on my device every time GameOver was called. Easy fix.

**Comment by dionlarson** [comment]
Step already seems to be there.

https://github.com/MakeSchool-Tutorials/Sushi-Neko-SpriteBuilder-Swift/blame/104160f58656125049a092e97047b3f74b836a88/P3-Setup-Main-Scene/content.md#L65
